### 1. Testar se o servidor está vivo
GET https://back-end-presensee.onrender.com/api/status

### 2. Cadastrar a nossa primeira Turma
POST https://back-end-presensee.onrender.com/api/classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

{
  "name": "1º Ano A",
  "year": 2026,
  "course": "Ensino Médio",
  "shift": "Tarde"
}

### 3. Listar todas as Turmas cadastradas
GET https://back-end-presensee.onrender.com/api/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

### 4. Cadastrar um Aluno
POST https://back-end-presensee.onrender.com/api/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

{
  "registration": "2026001",
  "name": "João da Silva",
  "email": "joao@email.com",
  "birthDate": "2010-05-15T00:00:00Z",
  "classId": "cbef5ae3-93bd-41eb-b4e5-919d51874d72"
}

### 5. Listar todos os Alunos (com os dados da turma)
GET https://back-end-presensee.onrender.com/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

### 6. Registrar Chamada (Check-in da Câmera)
POST https://back-end-presensee.onrender.com/api/attendances
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro
Content-Type: application/json

{
  "studentId": "d8f10531-f504-4040-9087-db1c2a8927ad",
  "classId": "cbef5ae3-93bd-41eb-b4e5-919d51874d72",
  "status": "PRESENT"
}

### 7. Ver painel de Alertas
GET https://back-end-presensee.onrender.com/api/alerts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

### 8. Testar Upload de Biometria (Foto do Aluno)
PATCH https://back-end-presensee.onrender.com/api/students/d8f10531-f504-4040-9087-db1c2a8927ad/biometry
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="pedro.jpg"
Content-Type: image/jpeg

< C:/Users/Pedro/Downloads/PresenSee RF/alunos/pedro.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 9. Testar Listagem do Dashboard
GET https://back-end-presensee.onrender.com/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

### 10. Testar Histórico de Presença do Aluno
GET https://back-end-presensee.onrender.com/api/students/08d0fdce-61a4-4c5e-85ef-a2e4cded67bc/attendance-history?month=9&year=2026
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyNTc1ZTVlLTI3ZmYtNDdiOS04MmI1LWM3ZDA2Mzg4NTBjZiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiJQZWRybyBIZW5yaXF1ZSIsImlhdCI6MTc5MDA5NTg0NywiZXhwIjoxNzkwMTI0NjQ3fQ.4OTIW3wS4ouNvWWTolT5aubVeC2C1naUt0VsaDWXFro

### 11. Setup Temporário do Admin
POST https://back-end-presensee.onrender.com/api/admin/setup
Content-Type: application/json

{
  "name": "Pedro Henrique",
  "email": "admin@presensee.com",
  "password": "senha_segura_123",
  "role": "ADMIN"
}

### 12. Testar Login Oficial
POST https://back-end-presensee.onrender.com/api/login
Content-Type: application/json

{
  "email": "admin@presensee.com",
  "password": "senha_segura_123"
}